[theme]
base = "dark"
primaryColor = "#43e4ce"
backgroundColor = "#0b1220"
secondaryBackgroundColor = "#142138"
textColor = "#e8edf7"

[server]
maxUploadSize = 10
headless = true

[browser]
gatherUsageStats = false
