[theme]
base = "dark"
primaryColor = "#76d9cf"
backgroundColor = "#151e23"
secondaryBackgroundColor = "#202c34"
textColor = "#e8edf7"

[server]
maxUploadSize = 10
headless = true

[browser]
gatherUsageStats = false
